### ISSUE TITLE
Change findById for findByPk if sequelize version is greather than v5

### ISSUE THREAD

**Issue by alejandroalfonsoyero** [yeiniel/rest-hal-sequelize#26]
This project depends of "sequelize": "^4.44.3"
But since sequelize v5 was released, the model function findById was replaced with findByPk, resulting in the next error.

TypeError: this.model.findById is not a function
    at ResourceController.item (/usr/share/preferences-api/app/node_modules/@yeiniel/rest-hal-sequelize/src/controller/resource.js:42:20)

If you manually change the function name in .../node_modules/@yeiniel/rest-hal-sequelize/src/controller/resource.js the error disappears

**Comment by alejandroalfonsoyero** [comment]
You can see this question for references. https://stackoverflow.com/questions/41577597/sequelize-findbyid-is-not-a-function-but-apparently-findall-is

**Comment by yeiniel** [comment]
hey @alejandroalfonsoyero next time you can create a PR yourself. It will be appreciated and merged as soon as possible. No need to publish the fork on NPM.
